[tool.poetry]
name = "ros-launch-analyzer"
version = "0.1.0"
description = ""
authors = ["Daisuke Sato <tiryoh@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
graphviz = "^0.20.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
